### ISSUE TITLE
Version 2 is causing errors.

### ISSUE THREAD

**Issue by OnlyJuan** [navarr/ytaudio#5]
Tested on Chrome 43.0.2357.132 m.

Error message:
![Error](http://i.imgur.com/2GOMZwE.png)

Fix:
Line 811, change to version 1, tested on all mainstream browsers.

**Comment by navarr** [comment]
Version 1 renders video but the mini players don't render correctly.. YouTube may have stopped this from working!

**Comment by navarr** [comment]
The issue was the nocookie domain.  I've removed it from the generator.
